services:

  postgres:
    image: postgres:13-alpine
    ports:
      - '8818:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef